### ISSUE TITLE
Spurious obsolete warnings when running under Linux

### ISSUE THREAD

**Issue by agc93** [cake-contrib/Cake.DocFx#51] opened 2017-05-28 06:53 UTC
Running the new `DocFxBuild` alias under Mono results in a warning being printed that `Cake.DocFx.DocFxSettings` is obsolete.

Why is the settings class marked obsolete when the only aliases using it are also marked obsolete?

This can be reproduced by running `build.sh` from [this repo](https://github.com/agc93/docfx-warning-sample).

![screenshot from 2017-05-28 16-54-35](https://cloud.githubusercontent.com/assets/1369269/26526712/67e0881e-43c6-11e7-9bb0-50d60e281528.png)

**Comment by pascalberger** [comment] 2017-05-29 14:07
@agc93 What is the issue with `DocFxSettings` being made obsolete? The reason it was marked as obsolete was that the alias using it was also marked as obsolete and the class would serve no purpose if the alias was removed.

**Comment by agc93** [comment] 2017-05-30 11:58
The issue with the settings class being made obsolete is that you get build warnings even when using the new non-obsolete aliases. 

Obsoleting the alias without the settings class would still have the desired effect of a build warning when using the old aliases, while not causing the warnings this issue is raised for.

**Comment by pascalberger** [comment] 2017-06-05 08:06
This seems to be specific while compiling the script under Mono, I wasn't able to reproduce it on Windows.

**Closed** 2017-06-06 07:12 UTC
Labels: Bug

**Comment by agc93** [comment] 2017-06-06 22:02
Thanks for the fix!

Yeah, it's Mono-specific (hence the issue title) and wouldn't be the first Mono-specific oddity when working with Cake 👍
